DROP TABLE IF EXISTS groupmembers CASCADE;
CREATE TABLE groupmembers (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE
);